services:
  _defaults:
    autowire: true
    public: true

  D3\OxidServiceBridges\Internal\Framework\Module\Path\ModulePathResolverBridgeInterface:
    class: D3\OxidServiceBridges\Internal\Framework\Module\Path\ModulePathResolverBridge

  D3\OxidServiceBridges\Smarty\Module\Setup\EventSubscriber\InstallSmartyExtensionEventsSubscriberBridgeInterface:
    class: D3\OxidServiceBridges\Smarty\Module\Setup\EventSubscriber\InstallSmartyExtensionEventsSubscriberBridge

  OxidEsales\Smarty\Module\Setup\EventSubscriber\InstallSmartyExtensionEventsSubscriber:
    alias: 'oxid_esales.smarty.setup.eventsubscriber.install_smarty_extension_events_subscriber'