services:
  _defaults:
    autowire: true
    public: true

  D3\OxidServiceBridges\Internal\Framework\Module\Path\ModulePathResolverBridgeInterface:
    class: D3\OxidServiceBridges\Internal\Framework\Module\Path\ModulePathResolverBridge
