services:
  _defaults:
    autowire: false
    public: true

  D3\OxidServiceBridges\Internal\Framework\Module\Path\ModulePathResolverBridgeInterface:
    class: D3\OxidServiceBridges\Internal\Framework\Module\Path\ModulePathResolverBridge

  D3\OxidServiceBridges\Smarty\Module\Setup\EventSubscriber\InstallSmartyExtensionEventsSubscriberBridgeInterface:
    class: D3\OxidServiceBridges\Smarty\Module\Setup\EventSubscriber\InstallSmartyExtensionEventsSubscriberBridge

  OxidEsales\Smarty\Module\Setup\EventSubscriber\InstallSmartyExtensionEventsSubscriber:
    alias: 'oxid_esales.smarty.setup.eventsubscriber.install_smarty_extension_events_subscriber'

  D3\OxidServiceBridges\Internal\Framework\Module\Cache\InvalidateModuleCacheEventSubscriberBridgeInterface:
    class: D3\OxidServiceBridges\Internal\Framework\Module\Cache\InvalidateModuleCacheEventSubscriberBridge
    
  OxidEsales\EshopCommunity\Internal\Framework\Module\Cache\InvalidateModuleCacheEventSubscriber:
    alias: 'oxid_esales.module.cache.invalidate_module_cache_event_subscriber'